### ISSUE TITLE
sulley bug?

### ISSUE THREAD

**Issue by xiaoyanguoke** [OpenRCE/sulley#107]
root@kali:~# python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from sulley import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sulley/__init__.py", line 1, in <module>
    from sulley import Sulley
  File "/usr/local/lib/python2.7/dist-packages/sulley/sulley.py", line 9, in <module>
    from providers import twilio, plivo
ImportError: No module named providers

this can resolve?

**Comment by Fitblip** [comment]
It appears that you installed https://github.com/sandeepraju/sulley from pypi, not Sulley from this repo.

**Comment by xiaoyanguoke** [comment]
can you help me ?

**Comment by samsempiol** [comment]
Same issue for me. I solved with:

1- git clone https://github.com/sandeepraju/sulley
2- cd sulley/sulley
3- edit the file called sulley.py
4- replace "from providers import twilio, plivo" to "import twilio, plivo"
5- cd ..; python setup.py install
