### ISSUE TITLE
unit_test.py fails in blocks.dependencies()

### ISSUE THREAD

**Issue by jimmers** [OpenRCE/sulley#47]
C:\sulley_build\sulley>unit_test.py
PRIMITIVE MUTATION COUNTS (SIZES):
        delim:  44      (3979)
        string: 1078    (72904962)
        byte:   112
        word:   141
        dword:  143
        qword:  143
        sizer:  143
Traceback (most recent call last):
  File "C:\sulley_build\sulley\unit_test.py", line 5, in <module>
    unit_tests.blocks.run()
  File "C:\sulley_build\sulley\unit_tests\blocks.py", line 5, in run
    dependencies()
  File "C:\sulley_build\sulley\unit_tests\blocks.py", line 89, in dependencies
    assert(s_render().find("ONE") == -1)
AssertionError

**Comment by SteveJM** [comment]
Ahhh, I had this and fixed it in pull request earlier today.
The test required a "s_mutate()" prior to the first assert.

Therefore this issue can now be closed.
