### ISSUE TITLE
signal module doesn't have pause method in Python 2.7 for Windows

### ISSUE THREAD

**Issue by jimmers** [OpenRCE/sulley#49]
Traceback (most recent call last):
  File "C:\SE\login.py", line 25, in <module>
    sess.fuzz()
  File "C:\sulley_build\sulley\sulley\sessions.py", line 540, in fuzz
    self.fuzz(self.fuzz_node, path)
  File "C:\sulley_build\sulley\sulley\sessions.py", line 553, in fuzz
    signal.pause()
AttributeError: 'module' object has no attribute 'pause'

**Comment by juniorprincewang** [comment]
Is there any solution about this issue? My system is  win7 64bits.

**Comment by jtpereyda** [comment]
I made a pull request but what worked for me is to catch the exception and loop instead:

```diff
diff --git a/sulley/sessions.py b/sulley/sessions.py
index 64d8c4c..5f0921c 100644
--- a/sulley/sessions.py
+++ b/sulley/sessions.py
@@ -551,8 +551,13 @@ class session (pgraph.graph):
             # if fuzzing is not finished, web interface thread will catch it
             if self.total_mutant_index == self.total_num_mutations:
                 import signal
-                while True:
-                    signal.pause()
+                try:
+                    while True:
+                        signal.pause()
+                except AttributeError:
+                    # signal.pause() is missing for Windows; wait 1ms and loop instead
+                    while True:
+                        time.sleep(1)


     ####################################################################################################################
```

**Comment by bicepjai** [comment]
Still having issue even after using @jtpereyda suggestion. Is [this stackoverflow post ](https://stackoverflow.com/questions/35772001/how-to-handle-the-signal-in-python-on-windows-machine) considered a fix ?

**Comment by codemaker2015** [comment]
The error AttributeError: module 'signal' has no attribute 'pause' occurs because signal.pause() is not available on Windows. It's a Unix-only function used to suspend the process until a signal is received.

To solve, Replace `signal.pause()` with a cross-platform wait using `threading.Event().wait(): `


For example:

```
   llm_thread = threading.Thread(
        target=lambda: run_server(llm_server, port=5001),
        daemon=True
    )
    llm_thread.start()

    try:
        print("Servers are running. Press Ctrl+C to stop.")
        # Wait indefinitely until interrupted
        while not stop_event.is_set():
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping servers...")
        stop_event.set()
        sys.exit(0)

```
